services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - laravel

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lab3
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge